<?php

namespace Database\Seeders;

use App\Models\CategorieProduit;
use App\Models\Pays;
use App\Models\Produit;
use App\Models\Utilisateur;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class GeovisionCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $countryId = Pays::query()->value('id_pays');
        $userId = Utilisateur::query()->value('id_utilisateur');

        if (!$countryId || !$userId) {
            $this->command?->warn('GeoVision ignoré: pays ou utilisateur manquant.');
            return;
        }

        $categories = $this->syncCategoryTree($this->categoryTree());

        foreach ($this->productCatalog() as $product) {
            $category = $categories[$product['category_slug']] ?? null;

            if (!$category) {
                $this->command?->warn(sprintf('Catégorie GeoVision introuvable pour "%s".', $product['title']));
                continue;
            }

            $this->syncProduct($product, $category, $countryId, $userId);
        }
    }

    /**
     * @param array<int, array<string, mixed>> $tree
     * @return array<string, CategorieProduit>
     */
    private function syncCategoryTree(array $tree, ?CategorieProduit $parent = null): array
    {
        $categories = [];

        foreach ($tree as $index => $node) {
            $payload = [
                'nom' => $node['nom'],
                'slug' => $node['slug'],
                'description' => $node['description'],
                'segment' => 'geovision',
                'image' => $node['image'],
                'image_url' => $node['image'],
                'parent_id' => $parent?->id_categorie,
                'ordre' => $node['ordre'] ?? (($index + 1) * 10),
                'actif' => true,
            ];

            $category = CategorieProduit::query()->updateOrCreate(
                ['slug' => $node['slug']],
                $payload
            );

            $categories[$node['slug']] = $category;

            if (!empty($node['children']) && is_array($node['children'])) {
                $categories = array_merge(
                    $categories,
                    $this->syncCategoryTree($node['children'], $category)
                );
            }
        }

        return $categories;
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function syncProduct(array $definition, CategorieProduit $category, string $countryId, string $userId): void
    {
        $product = Produit::query()
            ->where('slug', $definition['slug'])
            ->first();

        if (!$product && !empty($definition['legacy_slugs'])) {
            $product = Produit::query()
                ->whereIn('slug', $definition['legacy_slugs'])
                ->first();
        }

        $payload = [
            'titre' => $definition['title'],
            'slug' => $definition['slug'],
            'reference' => $definition['reference'],
            'description' => $definition['description'],
            'description_courte' => $definition['short_description'],
            'prix' => $definition['price'],
            'prix_promo' => $definition['promo_price'] ?? null,
            'stock' => $definition['stock'] ?? 8,
            'stock_alerte' => $definition['stock_alert'] ?? 2,
            'statut' => $definition['status'] ?? 'disponible',
            'marque' => $definition['brand'] ?? 'GeoVision',
            'modele' => $definition['model'],
            'garantie' => $definition['warranty'] ?? '3 ans',
            'est_en_vedette' => (bool) ($definition['featured'] ?? false),
            'est_nouveau' => (bool) ($definition['new'] ?? true),
            'en_promo' => (bool) ($definition['promo'] ?? false),
            'vues' => $definition['views'] ?? 0,
            'note_moyenne' => $definition['rating'] ?? 0,
            'nombre_avis' => $definition['reviews'] ?? 0,
            'specifications' => [
                'overview' => $definition['overview'],
                'tags' => $definition['tags'] ?? [],
                'features' => $definition['features'] ?? [],
                'platforms' => $definition['platforms'] ?? [],
                'use_cases' => $definition['use_cases'] ?? [],
                'detail_notes' => $definition['detail_notes'] ?? [],
                'source_url' => $definition['source_url'] ?? null,
                'technical_specs' => $definition['technical_specs'] ?? [],
                'taxonomy' => $definition['taxonomy'] ?? [],
            ],
            'id_categorie' => $category->id_categorie,
            'id_pays' => $countryId,
            'id_utilisateur' => $userId,
            'date_creation' => now(),
        ];

        if ($product) {
            $product->fill($payload);
            $product->save();
        } else {
            $product = Produit::query()->create($payload);
        }

        $this->syncImages($product->id_produit, $definition['title'], $definition['images'] ?? []);
    }

    /**
     * @param array<int, string> $images
     */
    private function syncImages(string $productId, string $title, array $images): void
    {
        DB::table('images')
            ->where('imageable_type', 'PRODUIT')
            ->where('imageable_id', $productId)
            ->delete();

        foreach (array_values(array_unique(array_filter($images))) as $index => $image) {
            DB::table('images')->insert([
                'id_image' => Str::uuid()->toString(),
                'url' => $image,
                'path' => ltrim($image, '/'),
                'alt' => sprintf('%s - visuel %d', $title, $index + 1),
                'imageable_type' => 'PRODUIT',
                'imageable_id' => $productId,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function categoryTree(): array
    {
        return [
            [
                'nom' => 'Caméras',
                'slug' => 'geovision-cameras',
                'description' => 'Caméras IP, thermiques, multispectrales et intelligentes pour la vidéosurveillance professionnelle.',
                'image' => '/images/geovision/cam/cam1.webp',
                'ordre' => 10,
                'children' => [
                    [
                        'nom' => 'Caméra IP',
                        'slug' => 'geovision-camera-ip',
                        'description' => 'Caméras réseau haute définition pour sites critiques, retail, industrie et transport.',
                        'image' => '/images/geovision/cam/cam1.webp',
                        'ordre' => 10,
                        'children' => [
                            [
                                'nom' => 'Dôme',
                                'slug' => 'geovision-camera-ip-dome',
                                'description' => 'Dômes IP anti-vandalisme pour surveillance indoor et outdoor.',
                                'image' => '/images/geovision/cam/cam1.webp',
                            ],
                            [
                                'nom' => 'Bullet',
                                'slug' => 'geovision-camera-ip-bullet',
                                'description' => 'Caméras bullet IP longue portée avec IR, WDR et PoE.',
                                'image' => '/images/geovision/cam/cam2.webp',
                            ],
                            [
                                'nom' => 'PTZ (motorisée)',
                                'slug' => 'geovision-camera-ip-ptz',
                                'description' => 'PTZ et speed domes pour tracking, zoom optique et supervision de périmètre.',
                                'image' => '/images/geovision/cam/cam3.webp',
                            ],
                            [
                                'nom' => 'Turret',
                                'slug' => 'geovision-camera-ip-turret',
                                'description' => 'Turrets compactes avec vision nocturne et analytics embarqués.',
                                'image' => '/images/geovision/cam/cam4.webp',
                            ],
                            [
                                'nom' => 'Fisheye (360°)',
                                'slug' => 'geovision-camera-ip-fisheye',
                                'description' => 'Caméras fisheye 180° / 360° pour halls, magasins et espaces ouverts.',
                                'image' => '/images/geovision/cam/cam5.webp',
                            ],
                        ],
                    ],
                    [
                        'nom' => 'Caméra analogique / HD',
                        'slug' => 'geovision-camera-analogique-hd',
                        'description' => 'Solutions HD analogiques et encodeurs hybrides pour moderniser un parc existant.',
                        'image' => '/images/geovision/cam/cam2.webp',
                        'ordre' => 20,
                    ],
                    [
                        'nom' => 'Caméra thermique',
                        'slug' => 'geovision-camera-thermique',
                        'description' => 'Détection thermique, alerte incendie et protection périmétrique en environnement difficile.',
                        'image' => '/images/geovision/cam/cam3.webp',
                        'ordre' => 30,
                    ],
                    [
                        'nom' => 'Caméra multispectrale',
                        'slug' => 'geovision-camera-multispectrale',
                        'description' => 'Multi-capteurs et panoramiques pour couverture étendue avec analytique IA.',
                        'image' => '/images/geovision/cam/cam4.webp',
                        'ordre' => 40,
                    ],
                    [
                        'nom' => 'Caméra IA intelligente',
                        'slug' => 'geovision-camera-ia-intelligente',
                        'description' => 'Caméras cloud AI et deep learning pour humain, véhicule et événements avancés.',
                        'image' => '/images/geovision/cam/cam5.webp',
                        'ordre' => 50,
                    ],
                ],
            ],
            [
                'nom' => 'Enregistreurs & NVR',
                'slug' => 'geovision-enregistreurs-nvr',
                'description' => 'DVR, NVR, serveurs d’enregistrement et plateformes hybrides pour la rétention vidéo.',
                'image' => '/images/geovision/nvr/nvr1.webp',
                'ordre' => 20,
                'children' => [
                    [
                        'nom' => 'DVR (analogique)',
                        'slug' => 'geovision-dvr',
                        'description' => 'Enregistreurs analogiques pour HD-TVI, HD-CVI, AHD et migration CCTV.',
                        'image' => '/images/geovision/nvr/nvr2.webp',
                        'ordre' => 10,
                    ],
                    [
                        'nom' => 'NVR (IP)',
                        'slug' => 'geovision-nvr',
                        'description' => 'NVR IP logiciels et matériels avec PoE, RAID et intégrations GeoVision.',
                        'image' => '/images/geovision/nvr/nvr1.webp',
                        'ordre' => 20,
                        'children' => [
                            [
                                'nom' => 'NVR standalone',
                                'slug' => 'geovision-nvr-standalone',
                                'description' => 'NVR autonomes pour déploiements rapides mono-site.',
                                'image' => '/images/geovision/nvr/nvr1.webp',
                            ],
                            [
                                'nom' => 'NVR avec PoE intégré',
                                'slug' => 'geovision-nvr-poe-integre',
                                'description' => 'NVR compacts avec ports PoE intégrés pour simplifier le câblage.',
                                'image' => '/images/geovision/nvr/nvr3.webp',
                            ],
                            [
                                'nom' => 'NVR serveur (rack)',
                                'slug' => 'geovision-nvr-serveur-rack',
                                'description' => 'Serveurs rack pour plus de canaux, plus de stockage et plus de redondance.',
                                'image' => '/images/geovision/nvr/nvr5.webp',
                            ],
                        ],
                    ],
                    [
                        'nom' => 'XVR (hybride)',
                        'slug' => 'geovision-xvr',
                        'description' => 'Plateformes hybrides analogique/IP pour migration progressive.',
                        'image' => '/images/geovision/nvr/nvr4.webp',
                        'ordre' => 30,
                    ],
                    [
                        'nom' => 'Cloud NVR',
                        'slug' => 'geovision-cloud-nvr',
                        'description' => 'Enregistrement centralisé et accès distants pour environnements multi-sites.',
                        'image' => '/images/geovision/solution1.webp',
                        'ordre' => 40,
                    ],
                ],
            ],
            [
                'nom' => 'VMS & Analytics',
                'slug' => 'geovision-vms-analytics',
                'description' => 'VMS local, cloud et analytique IA pour pilotage vidéo, événements et opérations.',
                'image' => '/images/geovision/solution1.webp',
                'ordre' => 30,
                'children' => [
                    [
                        'nom' => 'VMS local',
                        'slug' => 'geovision-vms-local',
                        'description' => 'Postes et plateformes de supervision sur site avec live, playback et e-map.',
                        'image' => '/images/geovision/solution1.webp',
                        'ordre' => 10,
                    ],
                    [
                        'nom' => 'VMS cloud',
                        'slug' => 'geovision-vms-cloud',
                        'description' => 'Supervision cloud centralisée pour caméras, événements et alarmes.',
                        'image' => '/images/geovision/solution1.webp',
                        'ordre' => 20,
                    ],
                    [
                        'nom' => 'VMS hybride',
                        'slug' => 'geovision-vms-hybride',
                        'description' => 'Architecture hybride combinant enregistrement local, cloud et mobilité.',
                        'image' => '/images/geovision/solution1.webp',
                        'ordre' => 30,
                    ],
                    [
                        'nom' => 'Analytics IA',
                        'slug' => 'geovision-analytics-ia',
                        'description' => 'Face recognition, people counting, intrusion et tableaux de bord événementiels.',
                        'image' => '/images/geovision/solution1.webp',
                        'ordre' => 40,
                    ],
                ],
            ],
            [
                'nom' => 'Contrôle d’accès',
                'slug' => 'geovision-controle-acces',
                'description' => 'Lecteurs, contrôleurs, biométrie, mobile et cloud pour bâtiments, parkings et sites sensibles.',
                'image' => '/images/geovision/controleur1.webp',
                'ordre' => 40,
                'children' => [
                    [
                        'nom' => 'Contrôle par badge',
                        'slug' => 'geovision-access-badge',
                        'description' => 'Contrôleurs et lecteurs RFID / NFC pour accès badge et carte.',
                        'image' => '/images/geovision/controleur1.webp',
                        'ordre' => 10,
                    ],
                    [
                        'nom' => 'Contrôle biométrique',
                        'slug' => 'geovision-access-biometrie',
                        'description' => 'Face recognition et double authentification pour zones réglementées.',
                        'image' => '/images/geovision/controleur1.webp',
                        'ordre' => 20,
                    ],
                    [
                        'nom' => 'Contrôle mobile (NFC / QR)',
                        'slug' => 'geovision-access-mobile',
                        'description' => 'Applications mobiles, QR et workflows visiteurs pour accès sans contact.',
                        'image' => '/images/geovision/controleur1.webp',
                        'ordre' => 30,
                    ],
                    [
                        'nom' => 'Contrôle cloud',
                        'slug' => 'geovision-access-cloud',
                        'description' => 'Supervision cloud des portes, badges, contrôleurs et alertes distantes.',
                        'image' => '/images/geovision/controleur1.webp',
                        'ordre' => 40,
                    ],
                ],
            ],
            [
                'nom' => 'LPR / ANPR',
                'slug' => 'geovision-lpr-anpr',
                'description' => 'Reconnaissance de plaques pour parkings, barrières, contrôle d’accès véhicule et trafic.',
                'image' => '/images/geovision/cam/cam2.webp',
                'ordre' => 50,
                'children' => [
                    [
                        'nom' => 'LPR caméra dédiée',
                        'slug' => 'geovision-lpr-camera-dediee',
                        'description' => 'Caméras LPR optimisées pour capture plaques jour / nuit et vitesses élevées.',
                        'image' => '/images/geovision/cam/cam2.webp',
                        'ordre' => 10,
                    ],
                    [
                        'nom' => 'LPR logiciel',
                        'slug' => 'geovision-lpr-logiciel',
                        'description' => 'Base de données véhicules, règles d’accès, anti-passback et supervision parking.',
                        'image' => '/images/geovision/solution1.webp',
                        'ordre' => 20,
                    ],
                    [
                        'nom' => 'LPR embarqué caméra',
                        'slug' => 'geovision-lpr-embarque',
                        'description' => 'Caméras LPR avec moteur deep learning embarqué et pilotage direct des barrières.',
                        'image' => '/images/geovision/cam/cam3.webp',
                        'ordre' => 30,
                    ],
                ],
            ],
            [
                'nom' => 'PoE & Réseau',
                'slug' => 'geovision-poe-reseau',
                'description' => 'Switches PoE, uplinks SFP et infrastructure réseau pour caméras, contrôleurs et IoT.',
                'image' => '/images/geovision/nvr/nvr4.webp',
                'ordre' => 60,
                'children' => [
                    [
                        'nom' => 'Switch PoE',
                        'slug' => 'geovision-switch-poe',
                        'description' => 'Switches compacts pour petits sites et edge surveillance.',
                        'image' => '/images/geovision/nvr/nvr4.webp',
                        'ordre' => 10,
                    ],
                    [
                        'nom' => 'Switch PoE+',
                        'slug' => 'geovision-switch-poe-plus',
                        'description' => 'Switches PoE+ gérés pour caméras, NVR et contrôleurs.',
                        'image' => '/images/geovision/nvr/nvr3.webp',
                        'ordre' => 20,
                    ],
                    [
                        'nom' => 'Switch PoE++ (haute puissance)',
                        'slug' => 'geovision-switch-poe-plus-plus',
                        'description' => 'Switches haute capacité pour charges élevées, agrégation et racks multi-caméras.',
                        'image' => '/images/geovision/nvr/nvr5.webp',
                        'ordre' => 30,
                    ],
                ],
            ],
            [
                'nom' => 'Murs d’images',
                'slug' => 'geovision-murs-images',
                'description' => 'Video wall, décodage, affichage multi-sources et supervision grands écrans.',
                'image' => '/images/geovision/ecran1.webp',
                'ordre' => 70,
                'children' => [
                    [
                        'nom' => 'Video wall LCD',
                        'slug' => 'geovision-video-wall-lcd',
                        'description' => 'Pilotage de murs 2x2, 3x3 et multi-sources depuis Control Center.',
                        'image' => '/images/geovision/ecran1.webp',
                        'ordre' => 10,
                    ],
                    [
                        'nom' => 'LED wall',
                        'slug' => 'geovision-led-wall',
                        'description' => 'Scénarios de supervision LED pleine surface et diffusion d’événements.',
                        'image' => '/images/geovision/ecran1.webp',
                        'ordre' => 20,
                    ],
                    [
                        'nom' => 'Moniteur professionnel',
                        'slug' => 'geovision-moniteur-pro',
                        'description' => 'Décodage HDMI / VGA, affichage 4K et monitorage multi-flux.',
                        'image' => '/images/geovision/ecran1.webp',
                        'ordre' => 30,
                    ],
                ],
            ],
            [
                'nom' => 'Accessoires',
                'slug' => 'geovision-accessoires',
                'description' => 'Supports, boîtiers, connectique, câblage, adaptateurs et alimentation.',
                'image' => '/images/geovision/controleur1.webp',
                'ordre' => 80,
                'children' => [
                    [
                        'nom' => 'Supports (mur / plafond)',
                        'slug' => 'geovision-supports',
                        'description' => 'Supports muraux, pendants et kits de fixation pour caméras et lecteurs.',
                        'image' => '/images/geovision/controleur1.webp',
                        'ordre' => 10,
                    ],
                    [
                        'nom' => 'Boîtiers étanches',
                        'slug' => 'geovision-boitiers-etanches',
                        'description' => 'Capots et protections outdoor pour lecteurs et panneaux biométriques.',
                        'image' => '/images/geovision/controleur1.webp',
                        'ordre' => 20,
                    ],
                    [
                        'nom' => 'Câbles (RJ45, coaxial, fibre)',
                        'slug' => 'geovision-cables',
                        'description' => 'Fibre, uplinks SFP et câbles adaptés aux infrastructures vidéo IP.',
                        'image' => '/images/geovision/nvr/nvr4.webp',
                        'ordre' => 30,
                    ],
                    [
                        'nom' => 'Connecteurs',
                        'slug' => 'geovision-connecteurs',
                        'description' => 'Interfaces RS-485, Wiegand et convertisseurs pour intégration terrain.',
                        'image' => '/images/geovision/controleur1.webp',
                        'ordre' => 40,
                    ],
                    [
                        'nom' => 'Alimentations',
                        'slug' => 'geovision-alimentations',
                        'description' => 'PoE adapters, alimentation DC et extensions d’énergie sur IP.',
                        'image' => '/images/geovision/nvr/nvr2.webp',
                        'ordre' => 50,
                    ],
                ],
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function productCatalog(): array
    {
        return [
            [
                'title' => 'GV-GVD4910',
                'slug' => 'geovision-gv-gvd4910',
                'legacy_slugs' => ['geovision-hikvision-ds-2cd2143g0-i'],
                'reference' => 'GV-GVD4910',
                'model' => 'GV-GVD4910',
                'category_slug' => 'geovision-camera-ip-dome',
                'description' => 'Caméra dôme IP anti-vandalisme 4MP avec WDR Pro, IR, PoE et analytics cloud AI pour sites exigeants.',
                'short_description' => 'Caméra IP / Dôme / 4MP / PoE / IR / IK10 / Cloud AI',
                'overview' => 'Le GV-GVD4910 est un dôme IP 4MP GeoVision pensé pour les environnements professionnels nécessitant une couverture fiable, une protection physique renforcée et des événements IA pertinents.',
                'features' => ['4MP', 'PoE', 'IR', 'IP67', 'IK10', 'Human & vehicle classification'],
                'technical_specs' => [
                    ['label' => 'Résolution', 'value' => '4 MP'],
                    ['label' => 'Capteur', 'value' => 'CMOS progressive scan'],
                    ['label' => 'Objectif', 'value' => '2.8 ~ 12 mm'],
                    ['label' => 'Compression', 'value' => 'H.265 / H.264 / MJPEG'],
                    ['label' => 'Protection', 'value' => 'IP67 / IK10'],
                    ['label' => 'Alimentation', 'value' => 'PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra IP', 'subcategory' => 'Dôme', 'series' => 'Cloud AI Deep-Learning IP Camera'],
                'images' => ['/images/geovision/cam/cam1.webp', '/images/geovision/cam/cam4.webp'],
                'price' => 279000,
                'stock' => 14,
                'featured' => true,
            ],
            [
                'title' => 'GV-GBLF4802',
                'slug' => 'geovision-gv-gblf4802',
                'reference' => 'GV-GBLF4802',
                'model' => 'GV-GBLF4802',
                'category_slug' => 'geovision-camera-ip-bullet',
                'description' => 'Bullet IP 4MP full color avec warm LED, IR, PoE et classification humain / véhicule.',
                'short_description' => 'Caméra IP / Bullet / 4MP / Full color / PoE / AI',
                'overview' => 'Le GV-GBLF4802 couvre les sites extérieurs avec une image couleur de nuit, une portée IR solide et une analytique IA prête pour le périmètre.',
                'features' => ['4MP', 'Full color warm LED', 'PoE', 'IP67', 'IK10', 'AI perimeter protection'],
                'technical_specs' => [
                    ['label' => 'Résolution', 'value' => '4 MP'],
                    ['label' => 'Objectif', 'value' => '2.8 mm ou 3.6 mm'],
                    ['label' => 'Compression', 'value' => 'H.265 / H.264'],
                    ['label' => 'Vision nocturne', 'value' => 'Warm LED + IR'],
                    ['label' => 'Protection', 'value' => 'IP67 / IK10'],
                    ['label' => 'Alimentation', 'value' => 'PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra IP', 'subcategory' => 'Bullet', 'series' => 'AI Deep-Learning IP Camera'],
                'images' => ['/images/geovision/cam/cam2.webp'],
                'price' => 255000,
                'stock' => 11,
            ],
            [
                'title' => 'GV-SD4834-IR',
                'slug' => 'geovision-gv-sd4834-ir',
                'legacy_slugs' => ['geovision-speeddome-patrol-x32'],
                'reference' => 'GV-SD4834-IR',
                'model' => 'GV-SD4834-IR',
                'category_slug' => 'geovision-camera-ip-ptz',
                'description' => 'Speed dome IP 4MP avec zoom optique 33x, IR 150 m, WDR Pro, audio bidirectionnel et smart tracking.',
                'short_description' => 'Caméra IP / PTZ / 4MP / Zoom 33x / IR 150m / AI',
                'overview' => 'Le GV-SD4834-IR est conçu pour la surveillance périmétrique longue portée, les levées de doute rapides et le tracking sur grands sites.',
                'features' => ['Zoom optique 33x', 'IR 150 m', 'WDR Pro', 'Two-way audio', 'IK10', 'AI perimeter protection'],
                'technical_specs' => [
                    ['label' => 'Résolution', 'value' => '4 MP'],
                    ['label' => 'Zoom', 'value' => '33x optique'],
                    ['label' => 'IR', 'value' => '150 m'],
                    ['label' => 'Audio', 'value' => 'Bidirectionnel'],
                    ['label' => 'Protection', 'value' => 'IP66 / IK10'],
                    ['label' => 'Alimentation', 'value' => 'PoE+ / AC 24V / DC 24V'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra IP', 'subcategory' => 'PTZ (motorisée)', 'series' => 'IP Speed Dome'],
                'images' => ['/images/geovision/cam/cam3.webp'],
                'price' => 849000,
                'stock' => 6,
                'featured' => true,
            ],
            [
                'title' => 'GV-GEB4900',
                'slug' => 'geovision-gv-geb4900',
                'reference' => 'GV-GEB4900',
                'model' => 'GV-GEB4900',
                'category_slug' => 'geovision-camera-ip-turret',
                'description' => 'Eyeball dome 4MP cloud AI avec IR, WDR Pro, PoE et classification humain / véhicule.',
                'short_description' => 'Caméra IP / Turret / 4MP / PoE / IR / Cloud AI',
                'overview' => 'Le GV-GEB4900 apporte le format eyeball / turret GeoVision pour des projets nécessitant une pose discrète et une image stable en extérieur.',
                'features' => ['4MP', 'IR', 'PoE', 'IP67', 'IK10', 'Cloud AI'],
                'technical_specs' => [
                    ['label' => 'Résolution', 'value' => '4 MP'],
                    ['label' => 'Objectif', 'value' => '2.8 mm'],
                    ['label' => 'Compression', 'value' => 'H.265 / H.264'],
                    ['label' => 'Protection', 'value' => 'IP67 / IK10'],
                    ['label' => 'Détection IA', 'value' => 'Humain / véhicule'],
                    ['label' => 'Alimentation', 'value' => 'PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra IP', 'subcategory' => 'Turret', 'series' => 'Cloud AI Deep-Learning IP Camera'],
                'images' => ['/images/geovision/cam/cam4.webp'],
                'price' => 239000,
                'stock' => 10,
            ],
            [
                'title' => 'GV-GFER12800',
                'slug' => 'geovision-gv-gfer12800',
                'reference' => 'GV-GFER12800',
                'model' => 'GV-GFER12800',
                'category_slug' => 'geovision-camera-ip-fisheye',
                'description' => 'Caméra fisheye 12MP 180° / 360° avec dewarping on-edge, AI perimeter protection et PoE.',
                'short_description' => 'Caméra IP / Fisheye / 12MP / 360° / PoE / IK10',
                'overview' => 'Le GV-GFER12800 est idéal pour halls, commerces, zones d’accueil et open spaces où un large champ de vision réduit le nombre de caméras.',
                'features' => ['12MP', 'Fisheye 180° / 360°', 'On-edge dewarping', 'PoE', 'IP67', 'IK10'],
                'technical_specs' => [
                    ['label' => 'Résolution', 'value' => '12 MP'],
                    ['label' => 'Champ de vision', 'value' => '180° / 360°'],
                    ['label' => 'Compression', 'value' => 'H.265 / H.264'],
                    ['label' => 'Protection', 'value' => 'IP67 / IK10'],
                    ['label' => 'Fonction avancée', 'value' => 'Dewarping embarqué'],
                    ['label' => 'Alimentation', 'value' => 'PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra IP', 'subcategory' => 'Fisheye (360°)', 'series' => 'AI Deep-Learning IP Camera'],
                'images' => ['/images/geovision/cam/cam5.webp'],
                'price' => 595000,
                'stock' => 5,
            ],
            [
                'title' => 'GV-GVS2100',
                'slug' => 'geovision-gv-gvs2100',
                'reference' => 'GV-GVS2100',
                'model' => 'GV-GVS2100',
                'category_slug' => 'geovision-camera-analogique-hd',
                'description' => 'Encodeur vidéo H.265 combo 5MP pour TVI / AHD / CVI / CVBS, stockage local et analytics IA.',
                'short_description' => 'Vidéo server / HD analogique / 5MP / PoE / H.265',
                'overview' => 'Le GV-GVS2100 permet de faire évoluer un parc analogique vers un environnement hybride sans tout remplacer immédiatement.',
                'features' => ['TVI / AHD / CVI / CVBS', '5MP', 'H.265', 'Micro SD', 'PoE', 'Two-way audio'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Video Server / HD Encoder'],
                    ['label' => 'Résolution max', 'value' => '2592 x 1944'],
                    ['label' => 'Entrées / sorties', 'value' => '8 entrées capteurs / 4 sorties alarme'],
                    ['label' => 'Audio', 'value' => 'Bidirectionnel'],
                    ['label' => 'Stockage', 'value' => 'Micro SD'],
                    ['label' => 'Alimentation', 'value' => 'DC 12V / PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra analogique / HD', 'subcategory' => 'Video Encoder', 'series' => 'AI-Capable HD Video Encoder'],
                'images' => ['/images/geovision/cam/cam2.webp'],
                'price' => 219000,
                'stock' => 8,
            ],
            [
                'title' => 'GV-TMEB5800',
                'slug' => 'geovision-gv-tmeb5800',
                'legacy_slugs' => ['geovision-thermalguard-tv-640'],
                'reference' => 'GV-TMEB5800',
                'model' => 'GV-TMEB5800',
                'category_slug' => 'geovision-camera-thermique',
                'description' => 'Caméra thermique et optique 5MP avec détection feu, exception de température et alarmes son / lumière.',
                'short_description' => 'Caméra thermique / 5MP / Fire detection / PoE / Audio',
                'overview' => 'Le GV-TMEB5800 combine imagerie thermique et optique pour la prévention incendie, la détection de température anormale et la protection périmétrique.',
                'features' => ['Thermal + optical', 'Fire detection', 'Temperature exception alarm', 'PoE', 'Two-way audio', 'Built-in siren'],
                'technical_specs' => [
                    ['label' => 'Résolution optique', 'value' => '5 MP'],
                    ['label' => 'Thermique', 'value' => '256 x 192'],
                    ['label' => 'Spectre', 'value' => '8 ~ 14 um'],
                    ['label' => 'IR', 'value' => '30 m'],
                    ['label' => 'Protection', 'value' => 'IP66'],
                    ['label' => 'Alimentation', 'value' => 'DC 12V / PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra thermique', 'subcategory' => 'Thermal + Optical', 'series' => 'AI Deep-Learning IP Camera'],
                'images' => ['/images/geovision/cam/cam3.webp'],
                'price' => 1299000,
                'stock' => 3,
            ],
            [
                'title' => 'GV-TMS8800',
                'slug' => 'geovision-gv-tms8800',
                'reference' => 'GV-TMS8800',
                'model' => 'GV-TMS8800',
                'category_slug' => 'geovision-camera-multispectrale',
                'description' => 'Caméra double capteur 2 x 4MP pour vue panoramique 180°, AI perimeter protection et PoE.',
                'short_description' => 'Caméra multispectrale / 2 x 4MP / Panoramique 180° / PoE',
                'overview' => 'Le GV-TMS8800 fournit une couverture panoramique multi-capteurs idéale pour façades, parkings et longues zones d’observation.',
                'features' => ['Dual-sensor', '180° panoramic view', '2 x 4MP', 'PoE', 'IP67', 'IK10'],
                'technical_specs' => [
                    ['label' => 'Capteurs', 'value' => '2 x 4 MP CMOS'],
                    ['label' => 'Vue', 'value' => 'Panoramique 180°'],
                    ['label' => 'Compression', 'value' => 'H.265'],
                    ['label' => 'Protection', 'value' => 'IP67 / IK10'],
                    ['label' => 'IR', 'value' => 'LEDs intégrées'],
                    ['label' => 'Alimentation', 'value' => 'PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra multispectrale', 'subcategory' => 'Dual-sensor panoramic', 'series' => 'AI Deep-Learning IP Camera'],
                'images' => ['/images/geovision/cam/cam4.webp'],
                'price' => 699000,
                'stock' => 4,
            ],
            [
                'title' => 'GV-GEBN4800',
                'slug' => 'geovision-gv-gebn4800',
                'reference' => 'GV-GEBN4800',
                'model' => 'GV-GEBN4800',
                'category_slug' => 'geovision-camera-ia-intelligente',
                'description' => 'Eyeball dome cloud AI avec AI-ISP, warm LEDs et classification avancée en faible luminosité.',
                'short_description' => 'Caméra IA / 4MP / AI-ISP / Full color / PoE',
                'overview' => 'Le GV-GEBN4800 cible les environnements difficiles en basse lumière grâce à son AI-ISP et sa restitution couleur enrichie.',
                'features' => ['AI-ISP', '4MP', 'Warm LEDs', 'Cloud AI', 'PoE', 'Human & vehicle classification'],
                'technical_specs' => [
                    ['label' => 'Résolution', 'value' => '4 MP'],
                    ['label' => 'Fonction IA', 'value' => 'AI-ISP + classification'],
                    ['label' => 'Vision nocturne', 'value' => 'Full color'],
                    ['label' => 'Compression', 'value' => 'H.265'],
                    ['label' => 'Protection', 'value' => 'IP67'],
                    ['label' => 'Alimentation', 'value' => 'PoE'],
                ],
                'taxonomy' => ['family' => 'Caméras', 'category' => 'Caméra IA intelligente', 'subcategory' => 'AI Eyeball', 'series' => 'Cloud AI Deep-Learning IP Camera'],
                'images' => ['/images/geovision/cam/cam5.webp'],
                'price' => 329000,
                'stock' => 7,
                'new' => true,
            ],
            [
                'title' => 'GV-DVR 8CH HD Recorder',
                'slug' => 'geovision-gv-dvr-8ch-hd-recorder',
                'reference' => 'GV-DVR-8CH-HD',
                'model' => 'GV-DVR-8CH-HD',
                'category_slug' => 'geovision-dvr',
                'description' => 'DVR 8 canaux pour caméras analogiques HD avec sorties HDMI/VGA, compression H.265 et stockage extensible.',
                'short_description' => 'DVR / 8 canaux / H.265 / HDMI / VGA',
                'overview' => 'Ce DVR GeoVision sert de base de modernisation pour les installations analogiques existantes en conservant un budget maîtrisé.',
                'features' => ['8 canaux', 'H.265', 'HDMI / VGA', 'Playback', 'Recherche intelligente', 'Intégration GeoVision'],
                'technical_specs' => [
                    ['label' => 'Canaux', 'value' => '8'],
                    ['label' => 'Compression', 'value' => 'H.265 / H.264'],
                    ['label' => 'Stockage', 'value' => '2 baies SATA'],
                    ['label' => 'Sorties', 'value' => 'HDMI / VGA'],
                    ['label' => 'Débit', 'value' => 'Jusqu’à 80 Mbps'],
                    ['label' => 'RAID', 'value' => 'Non'],
                ],
                'taxonomy' => ['family' => 'Enregistreurs & NVR', 'category' => 'DVR (analogique)', 'subcategory' => 'Standalone DVR', 'series' => 'GeoVision DVR'],
                'images' => ['/images/geovision/nvr/nvr2.webp'],
                'price' => 379000,
                'stock' => 6,
            ],
            [
                'title' => 'GV-NVR',
                'slug' => 'geovision-gv-nvr',
                'reference' => 'GV-NVR',
                'model' => 'GV-NVR',
                'category_slug' => 'geovision-nvr-standalone',
                'description' => 'Logiciel NVR GeoVision jusqu’à 32 canaux IP avec analytics, intégration access control et LPR.',
                'short_description' => 'NVR logiciel / 32 canaux / IP / analytics',
                'overview' => 'GV-NVR apporte une base solide pour les environnements IP purs avec analytics, intégrations et extension vers des caméras tierces.',
                'features' => ['32 canaux IP', 'ONVIF / PSIA / RTSP', 'Analytics', 'LPR integration', 'Access control integration', 'Playback'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'NVR logiciel'],
                    ['label' => 'Canaux', 'value' => 'Jusqu’à 32 IP'],
                    ['label' => 'Intégrations', 'value' => 'LPR / POS / ATM / accès'],
                    ['label' => 'Protocoles', 'value' => 'ONVIF / PSIA / RTSP'],
                    ['label' => 'Déploiement', 'value' => 'Serveur local'],
                    ['label' => 'Usage', 'value' => 'Mono-site / multi-site'],
                ],
                'taxonomy' => ['family' => 'Enregistreurs & NVR', 'category' => 'NVR (IP)', 'subcategory' => 'NVR standalone', 'series' => 'Video Management Software'],
                'images' => ['/images/geovision/nvr/nvr1.webp'],
                'price' => 495000,
                'stock' => 9,
            ],
            [
                'title' => 'GV-SNVR1600',
                'slug' => 'geovision-gv-snvr1600',
                'reference' => 'GV-SNVR1600',
                'model' => 'GV-SNVR1600',
                'category_slug' => 'geovision-nvr-poe-integre',
                'description' => 'NVR matériel avec ports PoE intégrés, détection vidéo avancée et déploiement accéléré sur petits et moyens sites.',
                'short_description' => 'NVR / PoE intégré / HDMI / stockage local',
                'overview' => 'Le GV-SNVR1600 simplifie les déploiements terrain grâce à son format matériel prêt à installer et à sa connectique pensée pour l’IP surveillance.',
                'features' => ['PoE intégré', 'Live View', 'Playback', 'Dual monitor', 'Advanced motion detection', 'Fisheye dewarping'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Standalone NVR matériel'],
                    ['label' => 'Stockage', 'value' => 'Baies locales pour enregistrement'],
                    ['label' => 'Sorties', 'value' => 'HDMI / DisplayPort'],
                    ['label' => 'Analytics', 'value' => 'Motion / privacy / scene change'],
                    ['label' => 'Usage', 'value' => 'PME / agences / retail'],
                    ['label' => 'Déploiement', 'value' => 'Plug-and-play IP'],
                ],
                'taxonomy' => ['family' => 'Enregistreurs & NVR', 'category' => 'NVR (IP)', 'subcategory' => 'NVR avec PoE intégré', 'series' => 'GV-SNVR System'],
                'images' => ['/images/geovision/nvr/nvr3.webp'],
                'price' => 925000,
                'stock' => 4,
            ],
            [
                'title' => 'UVS-CUBE VMS HotSwap System',
                'slug' => 'geovision-uvs-cube-vms-hotswap-system',
                'reference' => 'UVS-CUBE-HOTSWAP',
                'model' => 'UVS-CUBE VMS HotSwap System',
                'category_slug' => 'geovision-nvr-serveur-rack',
                'description' => 'Système VMS hot-swap 4 baies jusqu’à 32 canaux IP, double affichage et capacité jusqu’à 72 To.',
                'short_description' => 'Serveur NVR / 32 canaux / 72 To / Hot-swap',
                'overview' => 'Le UVS-CUBE VMS HotSwap System cible les projets nécessitant plus de capacité, une maintenance facilitée et des usages VMS complets.',
                'features' => ['32 canaux IP', 'Hot-swap 4 baies', '72 To max', 'Dual monitor', 'GPU decoding', 'Backup'],
                'technical_specs' => [
                    ['label' => 'Canaux', 'value' => 'Jusqu’à 32 IP'],
                    ['label' => 'Stockage', 'value' => 'Jusqu’à 72 To'],
                    ['label' => 'Affichage', 'value' => 'DP / HDMI'],
                    ['label' => 'Réseau', 'value' => '2 x Gigabit LAN'],
                    ['label' => 'OS', 'value' => 'Windows 11 Pro 64 bit'],
                    ['label' => 'Format', 'value' => 'Serveur hot-swap 4 baies'],
                ],
                'taxonomy' => ['family' => 'Enregistreurs & NVR', 'category' => 'NVR (IP)', 'subcategory' => 'NVR serveur (rack)', 'series' => 'VMS Systems'],
                'images' => ['/images/geovision/nvr/nvr5.webp'],
                'price' => 2399000,
                'stock' => 2,
            ],
            [
                'title' => 'GV-XVR Hybrid 16',
                'slug' => 'geovision-gv-xvr-hybrid-16',
                'legacy_slugs' => ['geovision-gv-xvr-hybrid-16'],
                'reference' => 'GV-XVR-HYB-16',
                'model' => 'GV-XVR Hybrid 16',
                'category_slug' => 'geovision-xvr',
                'description' => 'Plateforme hybride 16 canaux pour faire cohabiter analogique HD et IP dans une seule base d’enregistrement.',
                'short_description' => 'XVR / 16 canaux / analogique + IP / H.265',
                'overview' => 'Le GV-XVR Hybrid 16 accompagne les migrations graduelles vers l’IP tout en conservant les investissements CCTV déjà en place.',
                'features' => ['16 canaux', 'Analogique + IP', 'H.265', 'HDMI', 'Playback', 'Recherche intelligente'],
                'technical_specs' => [
                    ['label' => 'Canaux', 'value' => '16'],
                    ['label' => 'Mode', 'value' => 'Hybride analogique / IP'],
                    ['label' => 'Compression', 'value' => 'H.265 / H.264'],
                    ['label' => 'Sorties', 'value' => 'HDMI / VGA'],
                    ['label' => 'Usage', 'value' => 'Migration progressive'],
                    ['label' => 'Stockage', 'value' => 'SATA multi-baies'],
                ],
                'taxonomy' => ['family' => 'Enregistreurs & NVR', 'category' => 'XVR (hybride)', 'subcategory' => 'XVR 16 canaux', 'series' => 'Hybrid Recorder'],
                'images' => ['/images/geovision/nvr/nvr4.webp'],
                'price' => 589000,
                'stock' => 5,
            ],
            [
                'title' => 'GV-Recording Server',
                'slug' => 'geovision-gv-recording-server',
                'reference' => 'GV-RECORDING-SERVER',
                'model' => 'GV-Recording Server',
                'category_slug' => 'geovision-cloud-nvr',
                'description' => 'Serveur d’enregistrement et de distribution vidéo pour environnements centralisés et architectures cloud / edge.',
                'short_description' => 'Cloud NVR / recording server / distribution vidéo',
                'overview' => 'GV-Recording Server centralise l’enregistrement, la distribution des flux et la montée en charge entre sites, VMS et cloud.',
                'features' => ['Central recording', 'Distribution up to 600 channels', 'Cloud-ready', 'Streaming management', 'Multi-site', 'Playback'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Recording / Video Gateway'],
                    ['label' => 'Distribution', 'value' => 'Jusqu’à 600 canaux'],
                    ['label' => 'Architecture', 'value' => 'Centralisée / cloud-ready'],
                    ['label' => 'Intégrations', 'value' => 'GV-NVR / GV-VMS / GV-Control Center'],
                    ['label' => 'Usage', 'value' => 'Multi-site / data center'],
                    ['label' => 'Déploiement', 'value' => 'Serveur Windows'],
                ],
                'taxonomy' => ['family' => 'Enregistreurs & NVR', 'category' => 'Cloud NVR', 'subcategory' => 'Recording Server', 'series' => 'Cloud / Integration'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 1450000,
                'stock' => 4,
            ],
            [
                'title' => 'GV-Control Center',
                'slug' => 'geovision-gv-control-center',
                'legacy_slugs' => ['geovision-vms-center'],
                'reference' => 'GV-CONTROL-CENTER',
                'model' => 'GV-Control Center',
                'category_slug' => 'geovision-vms-local',
                'description' => 'Plateforme de commandement et de supervision unifiée pour live, playback, e-map, I/O, accès et LPR.',
                'short_description' => 'VMS local / command center / 900 canaux / e-map',
                'overview' => 'GV-Control Center est la brique de supervision unifiée pour les SOC et postes centraux ayant besoin de tout piloter dans une seule interface.',
                'features' => ['Up to 900 channels', 'Live monitoring', 'Remote playback', '3D E-Map', 'I/O panel', 'Access & LPR monitoring'],
                'technical_specs' => [
                    ['label' => 'Canaux live', 'value' => 'Jusqu’à 900'],
                    ['label' => 'Fonctions', 'value' => 'Live / Playback / I-O / E-Map'],
                    ['label' => 'Événements', 'value' => 'Access / LPR / AI Watch / FR Watch'],
                    ['label' => 'Video wall', 'value' => 'Optionnel'],
                    ['label' => 'Déploiement', 'value' => 'Poste central / SOC'],
                    ['label' => 'Usage', 'value' => 'Monitoring unifié'],
                ],
                'taxonomy' => ['family' => 'VMS & Analytics', 'category' => 'VMS local', 'subcategory' => 'Unified command center', 'series' => 'Large Scale Monitoring'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 1180000,
                'stock' => 6,
                'featured' => true,
            ],
            [
                'title' => 'GV-Cloud VMS',
                'slug' => 'geovision-gv-cloud-vms',
                'reference' => 'GV-CLOUD-VMS',
                'model' => 'GV-Cloud VMS',
                'category_slug' => 'geovision-vms-cloud',
                'description' => 'Solution cloud de surveillance vidéo et data center pour live, playback et événements depuis le navigateur.',
                'short_description' => 'VMS cloud / centralisation / web / recordings cloud',
                'overview' => 'GV-Cloud VMS simplifie la supervision distribuée grâce à une plateforme cloud capable d’agréger sites, alarmes et enregistrements.',
                'features' => ['Cloud-based monitoring', 'Playback', 'Event search', 'Direct-to-cloud camera integration', 'Browser access', 'Scalable permissions'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Cloud-based VMS'],
                    ['label' => 'Accès', 'value' => 'Web browser'],
                    ['label' => 'Stockage', 'value' => 'Cloud recordings'],
                    ['label' => 'Intégration', 'value' => 'Direct-to-cloud / GV-Cloud Bridge'],
                    ['label' => 'Architecture', 'value' => 'Scalable multi-site'],
                    ['label' => 'Portail', 'value' => 'gvaicloud.com'],
                ],
                'taxonomy' => ['family' => 'VMS & Analytics', 'category' => 'VMS cloud', 'subcategory' => 'Cloud monitoring platform', 'series' => 'Integration'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 980000,
                'stock' => 8,
                'new' => true,
            ],
            [
                'title' => 'GV-Center V2',
                'slug' => 'geovision-gv-center-v2',
                'reference' => 'GV-CENTER-V2',
                'model' => 'GV-Center V2',
                'category_slug' => 'geovision-vms-hybride',
                'description' => 'Centre de monitoring central pour flux terrain, cloud bridge et environnements hybrides.',
                'short_description' => 'VMS hybride / central monitoring / cloud bridge',
                'overview' => 'GV-Center V2 relie les environnements edge, cloud et supervision centrale avec une logique d’agrégation des événements et flux.',
                'features' => ['Central monitoring', 'Cloud Bridge compatible', 'Hybrid architecture', 'Event management', 'Multi-host', 'GeoVision ecosystem'],
                'technical_specs' => [
                    ['label' => 'Architecture', 'value' => 'Hybride edge + cloud'],
                    ['label' => 'Compatibilité', 'value' => 'GV-Cloud Bridge / GV-VPN / GV-Cloud VMS'],
                    ['label' => 'Usage', 'value' => 'Multi-sites et supervision centralisée'],
                    ['label' => 'Accès', 'value' => 'Poste d’exploitation'],
                    ['label' => 'Fonctions', 'value' => 'Live / events / administration'],
                    ['label' => 'Mobilité', 'value' => 'Apps et services cloud compatibles'],
                ],
                'taxonomy' => ['family' => 'VMS & Analytics', 'category' => 'VMS hybride', 'subcategory' => 'Central monitoring', 'series' => 'Large Scale Monitoring'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 895000,
                'stock' => 5,
            ],
            [
                'title' => 'GV-VMS V20',
                'slug' => 'geovision-gv-vms-v20',
                'reference' => 'GV-VMS-V20',
                'model' => 'GV-VMS V20',
                'category_slug' => 'geovision-analytics-ia',
                'legacy_slugs' => ['geovision-vision-ai-analytics-suite'],
                'description' => 'Suite VMS IA avec reconnaissance faciale intégrée, analytics cloud et intégrations avancées GeoVision.',
                'short_description' => 'Analytics IA / VMS / face recognition / cloud ready',
                'overview' => 'GV-VMS V20 ajoute une couche IA forte à la supervision vidéo en combinant face recognition, événements analytiques et intégration cloud.',
                'features' => ['AI-powered VMS', 'Built-in face recognition', 'Analytics events', 'Cloud ready', 'Third-party IP support', 'Search intelligent'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'VMS IA'],
                    ['label' => 'Analytics', 'value' => 'FR / AI events / search'],
                    ['label' => 'Compatibilité', 'value' => 'GeoVision et tiers'],
                    ['label' => 'Usage', 'value' => 'Supervision + analytics'],
                    ['label' => 'Architecture', 'value' => 'Local / cloud'],
                    ['label' => 'Intégration', 'value' => 'FR cameras / GV-AI FR / cloud'],
                ],
                'taxonomy' => ['family' => 'VMS & Analytics', 'category' => 'Analytics IA', 'subcategory' => 'AI VMS suite', 'series' => 'VMS V20'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 1100000,
                'stock' => 7,
            ],
            [
                'title' => 'GV-CS1320',
                'slug' => 'geovision-gv-cs1320',
                'legacy_slugs' => ['geovision-securepass-rfid-r20'],
                'reference' => 'GV-CS1320',
                'model' => 'GV-CS1320',
                'category_slug' => 'geovision-access-badge',
                'description' => 'Contrôleur d’accès caméra 2MP avec lecteur intégré, interphonie, PoE+ et support jusqu’à 100 000 utilisateurs.',
                'short_description' => 'Contrôle badge / 2MP / lecteur intégré / PoE+ / intercom',
                'overview' => 'GV-CS1320 combine contrôle d’accès, vidéo et interphonie dans un seul boîtier pour simplifier le déploiement des entrées sécurisées.',
                'features' => ['Built-in reader', '2MP camera', 'PoE+', 'Intercom', '100000 users', 'IP66'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Camera Reader Controller'],
                    ['label' => 'Caméra', 'value' => '2 MP'],
                    ['label' => 'Lecteur', 'value' => '13.56 MHz ISO 14443A'],
                    ['label' => 'Utilisateurs', 'value' => 'Jusqu’à 100 000'],
                    ['label' => 'I/O', 'value' => '2 inputs / 1 relay'],
                    ['label' => 'Alimentation', 'value' => 'DC 12V / PoE+'],
                ],
                'taxonomy' => ['family' => 'Contrôle d’accès', 'category' => 'Contrôle par badge', 'subcategory' => 'Lecteur / contrôleur', 'series' => 'Access Controller'],
                'images' => ['/images/geovision/controleur1.webp'],
                'price' => 435000,
                'stock' => 8,
            ],
            [
                'title' => 'GV-FR Panel V2',
                'slug' => 'geovision-gv-fr-panel-v2',
                'legacy_slugs' => ['geovision-faceaccess-pro-x'],
                'reference' => 'GV-FR-PANEL-V2',
                'model' => 'GV-FR Panel V2',
                'category_slug' => 'geovision-access-biometrie',
                'description' => 'Panneau biométrique avec reconnaissance faciale, NFC et écran IPS 7 pouces.',
                'short_description' => 'Biométrie / face recognition / NFC / écran IPS',
                'overview' => 'GV-FR Panel V2 cible les accès sensibles en combinant reconnaissance faciale, NFC, liveness detection et workflow visiteur QR.',
                'features' => ['Face recognition', 'NFC', '7 inch IPS', 'Liveness detection', 'QR optional', 'Third-party Wiegand integration'],
                'technical_specs' => [
                    ['label' => 'Écran', 'value' => '7 pouces IPS'],
                    ['label' => 'Capacité visages', 'value' => '10 000'],
                    ['label' => 'Capacité cartes', 'value' => '10 000'],
                    ['label' => 'Logs', 'value' => '50 000 événements'],
                    ['label' => 'Authentification', 'value' => 'Face / carte / face + carte'],
                    ['label' => 'Lecteur', 'value' => 'NFC 13.56 MHz'],
                ],
                'taxonomy' => ['family' => 'Contrôle d’accès', 'category' => 'Contrôle biométrique', 'subcategory' => 'Face reader', 'series' => 'Face Recognition Panel'],
                'images' => ['/images/geovision/controleur1.webp'],
                'price' => 629000,
                'stock' => 5,
                'featured' => true,
            ],
            [
                'title' => 'GV-Access',
                'slug' => 'geovision-gv-access',
                'reference' => 'GV-ACCESS',
                'model' => 'GV-Access',
                'category_slug' => 'geovision-access-mobile',
                'description' => 'Application mobile GeoVision pour surveiller portes, contrôleurs, LPR, alertes et déverrouillage distant.',
                'short_description' => 'Accès mobile / app / NFC QR workflows / push notifications',
                'overview' => 'GV-Access apporte la couche mobile du contrôle d’accès GeoVision avec alertes, live view et actions distantes sur portes et barrières.',
                'features' => ['Mobile access', 'Push notifications', 'Door unlock', 'LPR gate control', 'Live view', 'Alert clearing'],
                'technical_specs' => [
                    ['label' => 'Plateformes', 'value' => 'iOS / Android'],
                    ['label' => 'Systèmes', 'value' => 'Jusqu’à 5 GV-ASManager'],
                    ['label' => 'Actions', 'value' => 'Unlock door / open gate / clear alerts'],
                    ['label' => 'Flux', 'value' => 'Live camera mapped to door or lane'],
                    ['label' => 'Notifications', 'value' => 'Accès / LPR / I/O / système'],
                    ['label' => 'Usage', 'value' => 'Exploitation mobile'],
                ],
                'taxonomy' => ['family' => 'Contrôle d’accès', 'category' => 'Contrôle mobile (NFC / QR)', 'subcategory' => 'Mobile App', 'series' => 'Access Control App'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 149000,
                'stock' => 20,
            ],
            [
                'title' => 'GV-Cloud Access Control',
                'slug' => 'geovision-gv-cloud-access-control',
                'reference' => 'GV-CLOUD-ACCESS',
                'model' => 'GV-Cloud Access Control',
                'category_slug' => 'geovision-access-cloud',
                'description' => 'Plateforme cloud pour monitoring et administration des contrôleurs, portes et événements d’accès.',
                'short_description' => 'Contrôle cloud / monitoring / multi-site / browser',
                'overview' => 'GV-Cloud Access Control permet de superviser plusieurs sites d’accès à distance avec une logique cloud et des passerelles dédiées.',
                'features' => ['Cloud monitoring', 'Multi-site', 'Browser management', 'Controller status', 'Door events', 'Snapshots and playback integration'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Cloud access platform'],
                    ['label' => 'Accès', 'value' => 'Web + services cloud'],
                    ['label' => 'Compatibilité', 'value' => 'GV-AS1620 / GV-AS Bridge / GV-Cloud Bridge'],
                    ['label' => 'Événements', 'value' => 'Porte / badge / alertes'],
                    ['label' => 'Multi-site', 'value' => 'Oui'],
                    ['label' => 'Usage', 'value' => 'Administration centralisée'],
                ],
                'taxonomy' => ['family' => 'Contrôle d’accès', 'category' => 'Contrôle cloud', 'subcategory' => 'Cloud platform', 'series' => 'Cloud Access Control'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 745000,
                'stock' => 6,
            ],
            [
                'title' => 'GV-LPR2812-DL',
                'slug' => 'geovision-gv-lpr2812-dl',
                'legacy_slugs' => ['geovision-platescan-lpr-4k-fixed'],
                'reference' => 'GV-LPR2812-DL',
                'model' => 'GV-LPR2812-DL',
                'category_slug' => 'geovision-lpr-camera-dediee',
                'description' => 'Caméra LPR 2MP avec zoom 10x, moteur deep learning embarqué et capture jusqu’à 100 km/h.',
                'short_description' => 'LPR dédiée / 2MP / zoom 10x / DL engine / jour-nuit',
                'overview' => 'GV-LPR2812-DL cible les barrières, parkings et voies d’accès avec une lecture plaque embarquée et une intégration directe aux automatismes.',
                'features' => ['Built-in LPR engine', 'Zoom 10x', 'Up to 100 km/h', 'Day/night', 'IP67', 'IK10'],
                'technical_specs' => [
                    ['label' => 'Résolution', 'value' => '2 MP'],
                    ['label' => 'Zoom', 'value' => '10x'],
                    ['label' => 'Vitesse véhicule', 'value' => 'Jusqu’à 100 km/h'],
                    ['label' => 'Base locale', 'value' => 'Base plaques embarquée'],
                    ['label' => 'Intégration', 'value' => 'GV-ASManager / barrière'],
                    ['label' => 'Protection', 'value' => 'IP67 / IK10'],
                ],
                'taxonomy' => ['family' => 'LPR / ANPR', 'category' => 'LPR caméra dédiée', 'subcategory' => 'Caméra LPR fixe', 'series' => 'IP LPR Camera'],
                'images' => ['/images/geovision/cam/cam2.webp'],
                'price' => 1190000,
                'stock' => 4,
            ],
            [
                'title' => 'GV-LPR',
                'slug' => 'geovision-gv-lpr',
                'reference' => 'GV-LPR',
                'model' => 'GV-LPR',
                'category_slug' => 'geovision-lpr-logiciel',
                'description' => 'Logiciel LPR GeoVision pour base véhicules, parking management, hotlists et supervision web.',
                'short_description' => 'LPR logiciel / base véhicules / parking / web',
                'overview' => 'GV-LPR ajoute une logique de régulation véhicule complète avec base plaques, durée de stationnement, hotlists et accès distants.',
                'features' => ['100000 vehicles', 'Hotlists', 'Parking management', 'GV-ASWeb', 'GV-Access support', 'Import/export'],
                'technical_specs' => [
                    ['label' => 'Capacité', 'value' => 'Jusqu’à 100 000 véhicules'],
                    ['label' => 'Sources', 'value' => 'Jusqu’à 255 unités LPR'],
                    ['label' => 'Canaux PC-based', 'value' => 'Jusqu’à 8 par DVR / VMS LPR'],
                    ['label' => 'Web', 'value' => 'Jusqu’à 100 connexions'],
                    ['label' => 'Fonctions', 'value' => 'Parking, hotlist, anti-passback'],
                    ['label' => 'Accès mobile', 'value' => 'GV-Access'],
                ],
                'taxonomy' => ['family' => 'LPR / ANPR', 'category' => 'LPR logiciel', 'subcategory' => 'Software', 'series' => 'License Plate Recognition'],
                'images' => ['/images/geovision/solution1.webp'],
                'price' => 685000,
                'stock' => 7,
            ],
            [
                'title' => 'GV-LPC2211',
                'slug' => 'geovision-gv-lpc2211',
                'legacy_slugs' => ['geovision-trafficzoom-anpr-ptz'],
                'reference' => 'GV-LPC2211',
                'model' => 'GV-LPC2211',
                'category_slug' => 'geovision-lpr-embarque',
                'description' => 'Caméra LPR IP avec moteur embarqué pour contrôle d’accès véhicule et barrières sans serveur dédié.',
                'short_description' => 'LPR embarqué / caméra IP / barrière / jour-nuit',
                'overview' => 'GV-LPC2211 convient aux voies d’accès nécessitant une décision rapide locale à partir d’une base de données véhicule et de règles d’autorisation.',
                'features' => ['On-edge LPR', 'Barrier integration', 'Vehicle database', 'Day/night capture', 'Network IP', 'Parking workflow'],
                'technical_specs' => [
                    ['label' => 'Mode', 'value' => 'Reconnaissance embarquée'],
                    ['label' => 'Usage', 'value' => 'Voie de parking / barrière'],
                    ['label' => 'Base', 'value' => 'Véhicules autorisés / refusés'],
                    ['label' => 'Intégration', 'value' => 'Barrière / automate'],
                    ['label' => 'Capture', 'value' => 'Jour / nuit'],
                    ['label' => 'Déploiement', 'value' => 'Edge camera'],
                ],
                'taxonomy' => ['family' => 'LPR / ANPR', 'category' => 'LPR embarqué caméra', 'subcategory' => 'Embedded LPR Camera', 'series' => 'IP LPR Camera'],
                'images' => ['/images/geovision/cam/cam3.webp'],
                'price' => 895000,
                'stock' => 4,
            ],
            [
                'title' => 'GV-APOE0400',
                'slug' => 'geovision-gv-apoe0400',
                'reference' => 'GV-APOE0400',
                'model' => 'GV-APOE0400',
                'category_slug' => 'geovision-switch-poe',
                'description' => 'Switch PoE compact 6 ports avec 4 ports PoE, budget 60 W et mode longue distance 250 m.',
                'short_description' => 'Switch PoE / 4 ports PoE / 60W / 250m',
                'overview' => 'GV-APOE0400 est adapté aux petits environnements IP où la simplicité prime sans sacrifier la portée terrain.',
                'features' => ['4 ports PoE', '60W budget', '250m PoE mode', 'Palm size metal case', 'IEEE 802.3af/at', 'Small network'],
                'technical_specs' => [
                    ['label' => 'Ports', 'value' => '6 ports / 4 PoE'],
                    ['label' => 'Budget PoE', 'value' => '60 W'],
                    ['label' => 'Norme', 'value' => 'IEEE 802.3af / at'],
                    ['label' => 'Distance', 'value' => 'Jusqu’à 250 m à 10 Mbps'],
                    ['label' => 'Gestion', 'value' => 'Unmanaged'],
                    ['label' => 'Format', 'value' => 'Desktop metal case'],
                ],
                'taxonomy' => ['family' => 'PoE & Réseau', 'category' => 'Switch PoE', 'subcategory' => 'Unmanaged', 'series' => 'PoE Solution'],
                'images' => ['/images/geovision/nvr/nvr4.webp'],
                'price' => 129000,
                'stock' => 9,
            ],
            [
                'title' => 'GV-POE0812',
                'slug' => 'geovision-gv-poe0812',
                'legacy_slugs' => ['geovision-switch-poe-plus-managed-8p'],
                'reference' => 'GV-POE0812',
                'model' => 'GV-POE0812',
                'category_slug' => 'geovision-switch-poe-plus',
                'description' => 'Switch PoE+ 8 ports gigabit avec 2 slots SFP, montage rack et pilotage web smart.',
                'short_description' => 'Switch PoE+ / 8 ports / SFP / web smart',
                'overview' => 'GV-POE0812 est pensé pour les architectures vidéo IP qui ont besoin de plus de contrôle réseau, d’agrégation et de supervision.',
                'features' => ['8 ports Gigabit', 'PoE+', '2 SFP', 'Web Smart', 'Rack mount', 'VLAN / QoS'],
                'technical_specs' => [
                    ['label' => 'Ports', 'value' => '8 x RJ45 + 2 SFP'],
                    ['label' => 'Norme', 'value' => 'PoE+'],
                    ['label' => 'Gestion', 'value' => 'Web Smart'],
                    ['label' => 'Fonctions', 'value' => 'VLAN / QoS / sécurité'],
                    ['label' => 'Format', 'value' => 'Rack'],
                    ['label' => 'Usage', 'value' => 'Petits et moyens sites'],
                ],
                'taxonomy' => ['family' => 'PoE & Réseau', 'category' => 'Switch PoE+', 'subcategory' => 'Managed', 'series' => 'Gigabit PoE Switch'],
                'images' => ['/images/geovision/nvr/nvr3.webp'],
                'price' => 349000,
                'stock' => 6,
            ],
            [
                'title' => 'GV-APOE4813',
                'slug' => 'geovision-gv-apoe4813',
                'legacy_slugs' => ['geovision-industrial-outdoor-poepp-24p'],
                'reference' => 'GV-APOE4813',
                'model' => 'GV-APOE4813',
                'category_slug' => 'geovision-switch-poe-plus-plus',
                'description' => 'Switch 48 ports PoE+ web managed avec uplinks SFP+ et budget jusqu’à 600 W pour grands déploiements.',
                'short_description' => 'Switch haute puissance / 48 ports / 600W / SFP+',
                'overview' => 'GV-APOE4813 répond aux besoins des racks multi-caméras et multi-sites avec une gestion avancée du réseau et une forte densité PoE.',
                'features' => ['48 ports', 'SFP+ uplinks', '600W budget', 'L3 web management', 'VLAN / QoS / LACP', 'Rack'],
                'technical_specs' => [
                    ['label' => 'Ports', 'value' => '48 x PoE+ + 6 x SFP+'],
                    ['label' => 'Budget PoE', 'value' => '500W / 600W selon alimentation'],
                    ['label' => 'Gestion', 'value' => 'L3 Web Management'],
                    ['label' => 'Fonctions', 'value' => 'VLAN / QoS / RSTP / IGMP / LACP'],
                    ['label' => 'Format', 'value' => '19 pouces rack'],
                    ['label' => 'Usage', 'value' => 'Moyens et grands réseaux'],
                ],
                'taxonomy' => ['family' => 'PoE & Réseau', 'category' => 'Switch PoE++ (haute puissance)', 'subcategory' => 'High-capacity managed', 'series' => 'PoE Solution'],
                'images' => ['/images/geovision/nvr/nvr5.webp'],
                'price' => 1299000,
                'stock' => 3,
            ],
            [
                'title' => 'GV-Video Wall',
                'slug' => 'geovision-gv-video-wall',
                'legacy_slugs' => ['geovision-video-wall-control-2x2'],
                'reference' => 'GV-VIDEO-WALL',
                'model' => 'GV-Video Wall',
                'category_slug' => 'geovision-video-wall-lcd',
                'description' => 'Serveur de video wall piloté par GV-Control Center pour affichage multi-moniteurs jusqu’à 288 canaux.',
                'short_description' => 'Video wall / LCD / multi-moniteurs / 288 canaux',
                'overview' => 'GV-Video Wall permet d’orchestrer des murs d’images multi-écrans et de diffuser des sources IP à grande échelle depuis Control Center.',
                'features' => ['Up to 288 channels', 'Multi-monitor layouts', 'Zoom windows', 'Scan windows', 'Web windows', 'Remote monitor regions'],
                'technical_specs' => [
                    ['label' => 'Canaux', 'value' => 'Jusqu’à 288'],
                    ['label' => 'Layouts', 'value' => '2x2 / 3x3 / personnalisés'],
                    ['label' => 'Sources', 'value' => 'IP multi-sources'],
                    ['label' => 'Pilotage', 'value' => 'GV-Control Center'],
                    ['label' => 'Complément', 'value' => 'GV-Joystick compatible'],
                    ['label' => 'Usage', 'value' => 'SOC / salles de supervision'],
                ],
                'taxonomy' => ['family' => 'Murs d’images', 'category' => 'Video wall LCD', 'subcategory' => 'Video Wall Server', 'series' => 'Large Scale Monitoring'],
                'images' => ['/images/geovision/ecran1.webp'],
                'price' => 1195000,
                'stock' => 4,
            ],
            [
                'title' => 'GV-Control Center + GV-Video Wall',
                'slug' => 'geovision-gv-control-center-video-wall-bundle',
                'legacy_slugs' => ['geovision-led-wall-supervision-4k'],
                'reference' => 'GV-CC-VW-BUNDLE',
                'model' => 'GV-Control Center + GV-Video Wall',
                'category_slug' => 'geovision-led-wall',
                'description' => 'Bundle supervision centralisée et video wall pour grandes surfaces d’affichage et sites critiques.',
                'short_description' => 'LED wall / bundle supervision / video wall',
                'overview' => 'Cette combinaison est adaptée aux grands centres de contrôle ayant besoin de supervision centralisée et d’un affichage massif des événements.',
                'features' => ['Unified supervision', 'Video wall bundle', 'Event visualization', 'Remote management', 'Control center integration', 'Multi-source display'],
                'technical_specs' => [
                    ['label' => 'Architecture', 'value' => 'Control Center + Video Wall'],
                    ['label' => 'Affichage', 'value' => 'Multi-écrans / grand format'],
                    ['label' => 'Sources', 'value' => 'Caméras / web / playback / médias'],
                    ['label' => 'Usage', 'value' => 'Salles de crise / SOC / LED wall'],
                    ['label' => 'Pilotage', 'value' => 'Centralisé'],
                    ['label' => 'Événements', 'value' => 'Live / alertes / LPR / accès'],
                ],
                'taxonomy' => ['family' => 'Murs d’images', 'category' => 'LED wall', 'subcategory' => 'Supervision bundle', 'series' => 'Large Scale Monitoring'],
                'images' => ['/images/geovision/ecran1.webp'],
                'price' => 1695000,
                'stock' => 3,
            ],
            [
                'title' => 'GV-IP Display 116',
                'slug' => 'geovision-gv-ip-display-116',
                'reference' => 'GV-IP-DISPLAY-116',
                'model' => 'GV-IP Display 116',
                'category_slug' => 'geovision-moniteur-pro',
                'description' => 'Décodeur vidéo pour affichage HDMI avec jusqu’à 64 flux IP et support 8MP.',
                'short_description' => 'Moniteur pro / IP decoder / HDMI / 64 flux',
                'overview' => 'GV-IP Display 116 permet de créer un affichage pro simple et robuste pour supervision locale ou affichage déporté.',
                'features' => ['64 IP streams', 'Up to 8MP', 'HDMI / VGA', 'Snapshot', 'Pause on event', 'PTZ control via joystick'],
                'technical_specs' => [
                    ['label' => 'Décodage', 'value' => 'Jusqu’à 64 flux IP'],
                    ['label' => 'Résolution', 'value' => 'Jusqu’à 8 MP'],
                    ['label' => 'Sorties', 'value' => 'HDMI / VGA'],
                    ['label' => 'Compatibilité', 'value' => 'RTSP / ONVIF'],
                    ['label' => 'Usage', 'value' => 'Affichage pro / salle de contrôle'],
                    ['label' => 'Contrôle PTZ', 'value' => 'Oui via joystick'],
                ],
                'taxonomy' => ['family' => 'Murs d’images', 'category' => 'Moniteur professionnel', 'subcategory' => 'Decoder Box', 'series' => 'Standalone & Decoder'],
                'images' => ['/images/geovision/ecran1.webp'],
                'price' => 559000,
                'stock' => 5,
            ],
            [
                'title' => 'GV-Mount210-2',
                'slug' => 'geovision-gv-mount210-2',
                'legacy_slugs' => ['geovision-support-mural-renforce-ptz'],
                'reference' => 'GV-MOUNT210-2',
                'model' => 'GV-Mount210-2',
                'category_slug' => 'geovision-supports',
                'description' => 'Support mural / pendant pour caméras GeoVision, adapté aux installations extérieures et plafonds techniques.',
                'short_description' => 'Support mural / plafond / montage caméra',
                'overview' => 'GV-Mount210-2 simplifie les montages propres et robustes des caméras IP sur façade, plafond et mâts adaptés.',
                'features' => ['Wall pendant mount', 'Outdoor compatible', 'Metal construction', 'Camera mounting', 'Clean cable routing'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Support mural / pendant'],
                    ['label' => 'Usage', 'value' => 'Caméras GeoVision IP'],
                    ['label' => 'Matière', 'value' => 'Métal'],
                    ['label' => 'Montage', 'value' => 'Mur / plafond selon kit'],
                    ['label' => 'Finition', 'value' => 'Usage extérieur'],
                    ['label' => 'Rôle', 'value' => 'Fixation & passage câble'],
                ],
                'taxonomy' => ['family' => 'Accessoires', 'category' => 'Supports (mur / plafond)', 'subcategory' => 'Mount kit', 'series' => 'Accessories'],
                'images' => ['/images/geovision/controleur1.webp'],
                'price' => 69000,
                'stock' => 18,
            ],
            [
                'title' => 'GV-Reader Weather Cover',
                'slug' => 'geovision-gv-reader-weather-cover',
                'legacy_slugs' => ['geovision-boite-etanche-ip67-pro'],
                'reference' => 'GV-READER-WC',
                'model' => 'GV-Reader Weather Cover',
                'category_slug' => 'geovision-boitiers-etanches',
                'description' => 'Capot de protection outdoor pour lecteurs GeoVision exposés aux intempéries.',
                'short_description' => 'Boîtier étanche / reader cover / outdoor',
                'overview' => 'GV-Reader Weather Cover ajoute une protection physique supplémentaire aux lecteurs déployés en environnement extérieur.',
                'features' => ['Outdoor protection', 'Reader weather cover', 'Ingress shielding', 'Easy installation'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Weather cover'],
                    ['label' => 'Usage', 'value' => 'Lecteurs GeoVision'],
                    ['label' => 'Environnement', 'value' => 'Outdoor'],
                    ['label' => 'Fonction', 'value' => 'Protection pluie / poussière'],
                    ['label' => 'Montage', 'value' => 'Wall mounted'],
                    ['label' => 'Compatibilité', 'value' => 'Readers GeoVision compatibles'],
                ],
                'taxonomy' => ['family' => 'Accessoires', 'category' => 'Boîtiers étanches', 'subcategory' => 'Protection reader', 'series' => 'Accessories'],
                'images' => ['/images/geovision/controleur1.webp'],
                'price' => 39000,
                'stock' => 22,
            ],
            [
                'title' => 'GV-LC10',
                'slug' => 'geovision-gv-lc10',
                'reference' => 'GV-LC10',
                'model' => 'GV-LC10',
                'category_slug' => 'geovision-cables',
                'description' => 'Transceiver SFP pour interfacer les switches GeoVision avec les liaisons fibre optique.',
                'short_description' => 'Fibre / SFP transceiver / uplink',
                'overview' => 'GV-LC10 est l’élément d’extension fibre pour les uplinks réseau et les architectures vidéo IP réparties.',
                'features' => ['SFP transceiver', 'Fiber uplink', 'Switch integration', 'Rack networking'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'SFP Transceiver'],
                    ['label' => 'Usage', 'value' => 'Uplink fibre pour switches'],
                    ['label' => 'Compatibilité', 'value' => 'Ports SFP GeoVision'],
                    ['label' => 'Rôle', 'value' => 'Interface cuivre / fibre'],
                    ['label' => 'Environnement', 'value' => 'Rack / réseau'],
                    ['label' => 'Catégorie', 'value' => 'Fibre optique'],
                ],
                'taxonomy' => ['family' => 'Accessoires', 'category' => 'Câbles (RJ45, coaxial, fibre)', 'subcategory' => 'Fibre / SFP', 'series' => 'PoE Solution Accessories'],
                'images' => ['/images/geovision/nvr/nvr4.webp'],
                'price' => 85000,
                'stock' => 15,
            ],
            [
                'title' => 'GV-WTR',
                'slug' => 'geovision-gv-wtr',
                'reference' => 'GV-WTR',
                'model' => 'GV-WTR',
                'category_slug' => 'geovision-connecteurs',
                'description' => 'Convertisseur Wiegand / RS-485 pour intégrer lecteurs et contrôleurs tiers à l’écosystème GeoVision.',
                'short_description' => 'Convertisseur / Wiegand / RS-485 / intégration',
                'overview' => 'GV-WTR facilite les raccordements hétérogènes entre lecteurs, contrôleurs et logiciels GeoVision lors des projets d’intégration.',
                'features' => ['Wiegand / RS-485 conversion', 'Third-party reader integration', 'Access control interoperability'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'Converter'],
                    ['label' => 'Interfaces', 'value' => 'Wiegand / RS-485'],
                    ['label' => 'Usage', 'value' => 'Contrôle d’accès'],
                    ['label' => 'Compatibilité', 'value' => 'Readers / controllers GeoVision et tiers'],
                    ['label' => 'Rôle', 'value' => 'Interfaçage protocolaire'],
                    ['label' => 'Déploiement', 'value' => 'Armoire / coffret contrôle'],
                ],
                'taxonomy' => ['family' => 'Accessoires', 'category' => 'Connecteurs', 'subcategory' => 'Protocol converter', 'series' => 'Access Control Accessories'],
                'images' => ['/images/geovision/controleur1.webp'],
                'price' => 99000,
                'stock' => 12,
            ],
            [
                'title' => 'GV-PA191',
                'slug' => 'geovision-gv-pa191',
                'legacy_slugs' => ['geovision-ups-rack-2000va-secure'],
                'reference' => 'GV-PA191',
                'model' => 'GV-PA191',
                'category_slug' => 'geovision-alimentations',
                'description' => 'Adaptateur PoE pour alimenter les dispositifs IP GeoVision via un seul câble Ethernet.',
                'short_description' => 'Alimentation / PoE adapter / caméra IP',
                'overview' => 'GV-PA191 apporte une solution d’alimentation simple pour les périphériques IP GeoVision nativement compatibles avec l’infrastructure Ethernet.',
                'features' => ['PoE adapter', 'Single cable power', 'IP device support', 'Simple deployment'],
                'technical_specs' => [
                    ['label' => 'Type', 'value' => 'PoE Adapter'],
                    ['label' => 'Usage', 'value' => 'Caméras et dispositifs IP'],
                    ['label' => 'Rôle', 'value' => 'Alimentation via Ethernet'],
                    ['label' => 'Déploiement', 'value' => 'Indoor / coffret technique'],
                    ['label' => 'Compatibilité', 'value' => 'Produits GeoVision compatibles'],
                    ['label' => 'Catégorie', 'value' => 'Power accessory'],
                ],
                'taxonomy' => ['family' => 'Accessoires', 'category' => 'Alimentations', 'subcategory' => 'PoE Adapter', 'series' => 'PoE Solution Accessories'],
                'images' => ['/images/geovision/nvr/nvr2.webp'],
                'price' => 55000,
                'stock' => 20,
            ],
        ];
    }
}
