export const PAGE_ALIASES = {
  Communication: "communication",
  Ingenierie: "ingenierie",
  Fiabilite: "Fiablite",
  Developpement: "DeveloppementApplications",
  PrestationDetail: "PrestationDetail",
};

export const PUBLIC_APP_ROUTES = [
  { path: "/", page: "Home" },
  { path: "/register", page: "Register" },
  { path: "/login", page: "Login" },
  { path: "/client/dashboard", page: "Dashboard" },
  { path: "/solutions", page: "Solutions" },
  { path: "/formations", page: "Formations" },
  { path: "/projets", page: "Projets" },
  { path: "/actualites", page: "Actualites" },
  { path: "/contact", page: "Contact" },
  { path: "/prestation/:slug", page: "PrestationDetail" },
  { path: "/details/:type/:slug", page: "DetailDomaine" },
  { path: "/inscription", page: "InscriptionFormulaire" },
  { path: "/devenir-vendeur", page: "DevenirVendeur" },
  { path: "/verify-otp", page: "OtpVerification" },
  { path: "/expertise", page: "Expertise" },
  { path: "/ingenierie", page: "Ingenierie" },
  { path: "/apropos", page: "Apropos" },
  { path: "/profile", page: "Profile" },
  { path: "/profile/edit", page: "EditProfile" },
  { path: "/profile/password", page: "ChangePassword" },
  { path: "/forgot-password", page: "ForgotPassword" },
  { path: "/reset-password", page: "ResetPassword" },
  { path: "/reset-password/:token", page: "ResetPassword" },
  { path: "/presence", page: "Presence" },
  { path: "/fiabilite", page: "Fiabilite" },
  { path: "/accompagnement", page: "Accompagnement" },
  { path: "/innovation", page: "Innovation" },
  { path: "/services", page: "Services" },
  { path: "/services/developpement", page: "Developpement" },
  { path: "/services/communication", page: "Communication" },
  { path: "/services/tpe", page: "Tpe" },
  { path: "/services/drones", page: "Drones" },
  { path: "/services/btp", page: "Btp" },
  { path: "/geovision", page: "Geovision" },
  { path: "/geovision/catalogue/:typeId", page: "GeovisionCatalogue" },
  { path: "/geovision/categorie/:slug", page: "GeovisionCategorie" },
  { path: "/geovision/produit/:slug", page: "GeovisionProduitDetail" },
  { path: "/mentions-legales", page: "MentionsLegales" },
  { path: "/politique-confidentialite", page: "Confidentialite" },
  { path: "/cgv", page: "Cgv" },
  { path: "/formations/etudiant", page: "Etudiant" },
  { path: "/formations/particulier", page: "Particulier" },
  { path: "/formations/entreprise", page: "Entreprise" },
  { path: "/formations/comptabilite-immobilisations", page: "ComptabiliteImmobilisations" },
  { path: "/formations/gestion-commerciale-stock", page: "GestionCommercialeStock" },
  { path: "/formations/microsoft-avance", page: "MicrosoftAvance" },
  { path: "/formations/video-surveillance", page: "VideoSurveillance" },
  { path: "/formations/:id/details", page: "FormationDetails" },
  { path: "/formations/:id/register", page: "FormationRegister" },
  { path: "/profile/formations", page: "MesFormations" },
  { path: "/profile/produits", page: "MesProduits" },
  { path: "/profile/commandes", page: "MesCommandes" },
  { path: "/paiement/:id", page: "PaymentPage" },
  { path: "/facture/:id", page: "FacturePage" },
  { path: "/formations/:id/paiement", page: "PaymentPage" },
  { path: "/produits", page: "Produit" },
  { path: "/produits/:id", page: "ProduitDetail" },
  { path: "/produits/recherche", page: "ProduitRecherche" },
  { path: "/favoris", page: "Favoris" },
  { path: "/panier", page: "Panier" },
  { path: "/promotions", page: "Promotions" },
];
