services:
  - type: web
    name: isd-afrik-backend
    runtime: docker
    plan: free
    repo: https://github.com/matchamekevin/LARAVEL-GROUPE-ISD-AFRIK.git
    branch: main
    dockerfilePath: Dockerfile.prod
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: ''
      - key: APP_URL
        value: 'https://isd-afrik-backend.onrender.com'
      - key: DATABASE_URL
        value: ''
