services:
  - type: web
    name: isd-afrik-backend
    env: docker
    plan: free
    repo: https://github.com/matchamekevin/LARAVEL-GROUPE-ISD-AFRIK.git
    branch: main
    dockerfilePath: Dockerfile.prod
    buildCommand: ''
    startCommand: ''
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: ''
      - key: APP_URL
        value: 'https://isd-afrik-backend.onrender.com'
      - key: DATABASE_URL
        value: ''
  - type: postgres
    name: isd-afrik-db
    plan: free
  - type: cron
    name: isd-afrik-keepalive
    schedule: "*/9 * * * *"
    command: "curl -fsS $APP_URL || true"
    env: docker
    envVars:
      - key: APP_URL
        value: 'https://isd-afrik-backend.onrender.com'
