[supervisord]
nodaemon=true
user=root

; Envoyer les logs vers stdout/stderr pour qu'ils apparaissent dans Render.
logfile=/dev/null
logfile_maxbytes=0


[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=root

[program:queue-worker]
command=/usr/local/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90 --env=production
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=root

[program:reverb]
command=/usr/local/bin/php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=8080 --no-interaction --env=production
autostart={{REVERB_ENABLED}}
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=root

[program:scheduler]
command=/usr/local/bin/php /var/www/html/artisan schedule:work --env=production
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
user=root
