[supervisord]
nodaemon=true
user=root


[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
user=root

[program:queue-worker]
command=/usr/local/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90 --env=production
autostart=true
autorestart=true
stderr_logfile=/var/log/queue-worker.err.log
stdout_logfile=/var/log/queue-worker.out.log
user=root

[program:scheduler]
command=/usr/local/bin/php /var/www/html/artisan schedule:work --env=production
autostart=true
autorestart=true
stderr_logfile=/var/log/scheduler.err.log
stdout_logfile=/var/log/scheduler.out.log
user=root
