export const ADMIN_NAV_ITEMS = [
  { to: "/", icon: "fas fa-chart-line", label: "Dashboard" },
  { to: "/users", icon: "fas fa-users", label: "Utilisateurs" },
  { to: "/products", icon: "fas fa-box", label: "Produits" },
  { to: "/orders", icon: "fas fa-shopping-cart", label: "Commandes" },
  { to: "/formations", icon: "fas fa-graduation-cap", label: "Formations" },
  { to: "/messages", icon: "fas fa-envelope", label: "Messages" },
  { to: "/catalogue", icon: "fas fa-puzzle-piece", label: "Catalogue" },
  { to: "/promotions", icon: "fas fa-images", label: "Promotions" },
  { to: "/marketing", icon: "fas fa-bullhorn", label: "Marketing Accueil" },
  { to: "/ingenierie-page", icon: "fas fa-sitemap", label: "Page Ingenierie" },
  { to: "/testimonials", icon: "fas fa-comments", label: "Avis Clients" },
  { to: "/collaborators", icon: "fas fa-handshake", label: "Collaborateurs" },
  { to: "/partners", icon: "fas fa-building", label: "Partenaires" },
  { to: "/settings", icon: "fas fa-gear", label: "Paramètres" },
];
